### ISSUE TITLE
I need to change the timezone of the database

### ISSUE THREAD

**Issue by iLeonelPerea** [moodlehq/moodle-php-apache#124]
Hello.

Can you help me to change the timezone of the database. Or how can I do..

tnks

**Comment by stronk7** [comment]
Sorry @iLeonelPerea ,

this github repository is, exclusively, about the php docker images we use to test Moodle. It doesn't contain any database per se.

So we need some more information about how you're using this image or which database are you using. In general, Moodle doesn't need any timezone in the databases because all the datetimes are stored as unix seconds (bigint), not database dates and/or times.

Ciao :-)
