### ISSUE TITLE
How to configure the moodledata directory to a directory on my host?

### ISSUE THREAD

**Issue by llagerlof** [moodlehq/moodle-php-apache#157]
I managed to run this Moodle and everything is working fine, acessing a external database. But now I am trying to configure moodle to point the container' directory `/var/www/moodledata` to a directory on my host, let's say, `/host/moodledata`.

Ex:

**This work (default moodledata inside the container):**

```bash
$ docker run --name moodle402 -p 8080:80 -v $PWD:/var/www/html moodlehq/moodle-php-apache:7.4
```

**This no work and I don't know why.** Moodle show the error: **error/An error occurred whilst communicating with the server**

```bash
$ docker run --name moodle402 -p 8080:80 \
-v $PWD:/var/www/html \
-v /host/moodledata:/var/www/moodledata \
moodlehq/moodle-php-apache:7.4
```

My Moodle config: 
```php
$CFG->dataroot  = '/var/www/moodledata';
```

The directory `/host/moodledata` has full permissions (777).

So, is there some "right" way to have moodledata on my host?

**Comment by andrewnicols** [comment]
At a guess it's because the directory is mounted as root, Apache as run as a non-root user (www-data), and owned by your own user on the host.

This is a docker query but I suspect it will be solved by either:
* changing ownership of the directory on your local system to match the webserver user
* changing which user the image runs as (much harder).
