### ISSUE TITLE
Docker fo production

### ISSUE THREAD

**Issue by asnawisaharuddin** [moodlehq/moodle-php-apache#18]
Hi,

Is it ok to use this image in production ?

**Comment by scara** [comment]
HI @asnawisaharuddin,
shortly, no.

Long response: the target here is test&dev purposes ONLY.
You could take more than one bit from here (and related repos), to start creating a production ready environment but you need to define first what should be the requirements for your prod env: plain docker (CE vs EE), k8s, openshift, _whatever_ unmanaged vs managed.

Then, you need to create immutable images i.e. code should go into the image being part of the version of the image and so on.
Backup and Restore should be part of the prod game including strategies to scale the services composing your Moodle ecosystem.

Lurk into the Moodle Community for more refs and ideas e.g. https://moodle.org/mod/forum/discuss.php?d=358082.

HTH,
Matteo

**Comment by asnawisaharuddin** [comment]
@scara  Thanks for the answer!

**Comment by jrjohnson** [comment]
Ideally there would be a base official production moodle image. It doesn't actually need to meet all of the requirements that @scara laid out, but it should be an easy extension point for those of us building our own images. Just having an official tested PHP install with extensions would let us extend that image and add our code, auth, and other production info on top. 

It would also serve as the base for the testing image as well.

**Comment by scara** [comment]
Hi @jrjohnson,
IMHO an official production ready moodle image should require a commercial agreement since what I consider as a production ready image should be maintained for each of its layers starting from the base OS, which could be expensive if properly done as well as dangerous if not, mainly for security issues.
On the positive side, the regressions are already addressed by the large set of unit and integration tests available in the Moodle docker ecosystem (https://github.com/moodlehq/moodle-docker).

The base image of this Moodle image is the official PHP standard image which is not maintained for security issues unless when a new PHP version will be released: IMHO it should be your own duty to keep the image up-to-date - read: OS - as well as the PHP extensions used by Moodle.

Adding a layer for updating the base OS here will:
1. increase the disk space usage in both the dev host and the CI host since there will always be a variable  layer: it could be the last but it will always add several MB of different versions of files on each update
1. require Moodle HQ to release a new image to cover security issues (time consuming)

Otherwise, you could actually use this image by adding two new layers, one for the OS updates, including the PHP extensions, and the latter for the Moodle code (including updates).

Disclaimer: I'm not involved w/ Moodle HQ so opinions here are mine 😉.

HTH,
Matteo
