### ISSUE TITLE
How To Enable igbinary Serializers for Redis?

### ISSUE THREAD

**Issue by andisugandi** [moodlehq/moodle-php-apache#182]
Hi all,

I am running Moodle 4.2.1 on Docker Swarm Cluster by using `moodlehq/moodle-php-apache:8.1` based container image.

This container runs PHP 8.1 with the available serializers for Redis are: `php` and `php` only.

```
php -i | grep -A 4 'Redis Support' 
```
```
Redis Support => enabled
Redis Version => 5.3.7
Redis Sentinel Version => 0.1
Available serializers => php, php
```

<img width="659" alt="02-A-no-redis-igbinary-support-on-moodlextc" src="https://github.com/moodlehq/moodle-php-apache/assets/2184391/78cc5bc1-7419-4c9e-a9ed-a7565bc5fcd3">

## Expected Serializers

The available serializers for Redis are: `php`, `json`, and `igbinary`:

```
Available serializers => php, json, igbinary
```
<img width="659" alt="01-A-enabled-redis-igbinary-support-on-moodlegn" src="https://github.com/moodlehq/moodle-php-apache/assets/2184391/b47dd250-0dcf-4c66-b718-a2e0f4115aee">

---
What do you suggest to solve the issue?

Any helps is very much appreciated.

Thank you in advance.

**Comment by stronk7** [comment]
Thanks for reporting this @andisugandi ,

I'll take a look because I think that recent PHP / Redis versions switched the default to not install the support for igbinary by default.

The reason is that, for PHP 8.0 and up, its PHP serializer was improved a lot and was comparable (or better) than the igbinary one (on fact, internally... it sounds to me that it's igbinary, no matter the extension is not installed).

So, while I'll try to make the igbinary serializer to be available for redis... I'd recommend you to do some perf. testing, because maybe the PHP one is now quicker.

Also, note that the `moodlehq/moodle-php-apache` images are intended for development, so they may come with settings not ideal for production environments, be warned!

Ciao :-)

**Comment by stronk7** [comment]
Note that this has been fixed and the images are being regenerated right now. It will take a few hours to get them available.

Ciao :-)
