### ISSUE TITLE
Update to use 'stretch' images

### ISSUE THREAD

**Issue by andrewnicols** [moodlehq/moodle-php-apache#21]
We should be able to update to use the apache-stretch images available for 7.0, and 7.1.
This will allow us to test things like sassc (currently untested as sassc is not available on jessie)

**Comment by stronk7** [comment]
Just detected that current images are not building anymore because some weeks ago the official default images moved from jessie to stretch, so our harcoded dependencies are not valid any more.

Applying a quick fix to all the branches to explicitly use the jessie variant until we have the stretch variants ready.

**Comment by andrewnicols** [comment]
I've updated these images to rebase them.
Might I suggest that we create some new branches, and new Docker tags for the stretch variants such that they can be tested with a full run on our CI infra?

**Comment by stronk7** [comment]
Closing this, we have added the php56-stretch, php70-stretch and php71-stretch branches, with their corresponding X.Y-stretch docker tags.

For now the default branches continue using jessie and, when stretch is tested enough we'll be creating the phpXY-jessie branches and getting rid of the current phpXY ones, so docker tags will define the defaults.

Ciao :-)
