### ISSUE TITLE
Forbidden You don't have permission to access / on this server.

### ISSUE THREAD

**Issue by abirmoy** [moodlehq/moodle-php-apache#66]
I have ran
 docker run --name web0 -p 8080:80  -v PWD:/var/www/html moodlehq/moodle-php-apache:7.1

then tried to access on http://localhost:8080/

but getting this error
Forbidden
You don't have permission to access / on this server.
Apache/2.4.25 (Debian) Server at localhost Port 8080

can somebody please guide me step by step??
I'm very new to docker and moodle. Im doing it for my assignment

thanks

**Comment by scara** [comment]
Hi @abirmoy,
you should post in the Development Community, https://moodle.org/mod/forum/view.php?id=55: it looks like your `$(pwd)` is empty, w/o Moodle code there.

BTW, if you want to run Moodle on your PC you can download the full stack from e.g. https://download.moodle.org/windows/ if you are running Windows on your local PC.

Otherwise, you can use Docker but you need to:
- point your browser to the Moodle Docker Toolbox, https://github.com/moodlehq/moodle-docker, which this image is part of
- download the code of the Moodle version you want to run e.g. https://download.moodle.org/download.php/stable37/moodle-3.7.1.tgz

If your goal is to have Moodle up&running to create some courses, you can get a free "limited" instance of Moodle via https://moodlecloud.com/app/en/.

HTH,
Matteo

**Comment by andrewnicols** [comment]
Closing as this is a support request.
