### ISSUE TITLE
Missing php extensions

### ISSUE THREAD

**Issue by andrewnicols** [moodlehq/moodle-php-apache#8]
We're currently missing extensions for:
* memcache
* mongodb

**Comment by danpoltawski** [comment]
They are being compiled on php56, they aren't on the php7 images because I don't think they are compatible.

https://github.com/danpoltawski/moodle-php-apache/blob/php56/root/tmp/setup/php-extensions.sh#L37

Although I missed them from the tests:
https://github.com/danpoltawski/moodle-php-apache/blob/php56/tests/fixtures/test.php

**Comment by scara** [comment]
Hi Dan,
`mongodb` (w/ `db`) is available for PHP 7.x: look at Remi's repo https://blog.remirepo.net/pages/PECL-extensions-RPM-status , one of my ref repos (RHEL/CentOS).
The same for `memcached`.

HTH,
Matteo

**Comment by danpoltawski** [comment]
https://tracker.moodle.org/browse/MDL-54592

**Comment by andrewnicols** [comment]
I have memcache on php7 from brew but perhaps we should remove it from core.

Not sure about mongo..?

**Comment by scara** [comment]
@danpoltawski:
> https://tracker.moodle.org/browse/MDL-54592

Forgive my ignorance :blush:.

**Comment by stronk7** [comment]
Hi guys,

I'm closing this as far as #16 has been in charge of adding as many of the missing/problematic extensions as possible. Think that we have achieved a good status there.

And memcache out from core, and memcached and mogodb working... I think this is done.

Ciao :-)
